#!/usr/bin/env python
"""Removes Tor routes for a given address"""

"""
   Copyright 2015 Sean Whalen
   Copyright 2015 Jacob Gajek

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

from argparse import ArgumentParser
import socket

SOCKPATH = "/tmp/routetor"

argparser = ArgumentParser(description=__doc__)
argparser.add_argument("address")
args = argparser.parse_args()

client = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
client.sendto("stop {0}".format(args.address), SOCKPATH)
